### PR TITLE
Mopidy 0.18 updates

### LINKED ISSUE #2: Не работает
```
sudo pip install Mopidy-VKontakte   
Requirement already satisfied (use --upgrade to upgrade): Mopidy-VKontakte in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from Mopidy-VKontakte)
Requirement already satisfied (use --upgrade to upgrade): Mopidy>=0.14 in /usr/local/lib/python2.7/dist-packages (from Mopidy-VKontakte)
Requirement already satisfied (use --upgrade to upgrade): Pykka>=1.1 in /usr/local/lib/python2.7/dist-packages (from Mopidy-VKontakte)
Cleaning up...
>mopidy                              
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==0.17.0', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 51, in main
    installed_extensions = ext.load_extensions()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/ext.py", line 125, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2025, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named mopidy_VKontakte

```

### PR DESCRIPTION
**Pull request by jodal**
Update to use new extension API and new backend class locations as the old ones will be removed in the near future. Also did some other minor changes to the readme just to keep it sync with other extensions. Fixed #2 and the tests so that the package became installable and I could verify the changes I did.

### CODE REVIEW

**Comment by jodal** [comment]
Any comments on this?

**Comment by svenstaro** [comment]
Looks like the original author doesn't really care. Perhaps you should fork this to mopidy-vkontakte2?

**Comment by jodal** [comment]
As I'm not a user of vk.com (never heard of it before this extensions was created) I have no interest at all in forking this project.

**Comment by sibuser** [comment]
Sorry... Didn't see your issues... Will fix the plugin

**Pull request merged**
